# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'M:\CGXLightingTools\cgxLightingTools\scripts\gui\uiSketch\horizontal.ui'
#
# Created: Sun Jul 14 22:55:11 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_miniLightingTools_MW(object):
    def setupUi(self, miniLightingTools_MW):
        miniLightingTools_MW.setObjectName("miniLightingTools_MW")
        miniLightingTools_MW.resize(392, 99)
        miniLightingTools_MW.setMinimumSize(QtCore.QSize(392, 99))
        miniLightingTools_MW.setMaximumSize(QtCore.QSize(10000, 10000))
        self.centralwidget = QtGui.QWidget(miniLightingTools_MW)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tools_GRIDLAY = QtGui.QGridLayout()
        self.tools_GRIDLAY.setObjectName("tools_GRIDLAY")
        self.simpleIsolate_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simpleIsolate_BTN.sizePolicy().hasHeightForWidth())
        self.simpleIsolate_BTN.setSizePolicy(sizePolicy)
        self.simpleIsolate_BTN.setMinimumSize(QtCore.QSize(32, 32))
        self.simpleIsolate_BTN.setMaximumSize(QtCore.QSize(32, 32))
        self.simpleIsolate_BTN.setText("")
        self.simpleIsolate_BTN.setObjectName("simpleIsolate_BTN")
        self.tools_GRIDLAY.addWidget(self.simpleIsolate_BTN, 0, 0, 1, 1)
        self.lookThru_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookThru_BTN.sizePolicy().hasHeightForWidth())
        self.lookThru_BTN.setSizePolicy(sizePolicy)
        self.lookThru_BTN.setMinimumSize(QtCore.QSize(32, 32))
        self.lookThru_BTN.setMaximumSize(QtCore.QSize(32, 32))
        self.lookThru_BTN.setText("")
        self.lookThru_BTN.setObjectName("lookThru_BTN")
        self.tools_GRIDLAY.addWidget(self.lookThru_BTN, 0, 1, 1, 1)
        self.aimLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aimLight_BTN.sizePolicy().hasHeightForWidth())
        self.aimLight_BTN.setSizePolicy(sizePolicy)
        self.aimLight_BTN.setMinimumSize(QtCore.QSize(32, 32))
        self.aimLight_BTN.setMaximumSize(QtCore.QSize(32, 32))
        self.aimLight_BTN.setText("")
        self.aimLight_BTN.setObjectName("aimLight_BTN")
        self.tools_GRIDLAY.addWidget(self.aimLight_BTN, 0, 2, 1, 1)
        self.specularConstrain_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.specularConstrain_BTN.sizePolicy().hasHeightForWidth())
        self.specularConstrain_BTN.setSizePolicy(sizePolicy)
        self.specularConstrain_BTN.setMinimumSize(QtCore.QSize(32, 32))
        self.specularConstrain_BTN.setMaximumSize(QtCore.QSize(32, 32))
        self.specularConstrain_BTN.setText("")
        self.specularConstrain_BTN.setObjectName("specularConstrain_BTN")
        self.tools_GRIDLAY.addWidget(self.specularConstrain_BTN, 0, 3, 2, 1)
        self.cleanUpCams_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleanUpCams_BTN.sizePolicy().hasHeightForWidth())
        self.cleanUpCams_BTN.setSizePolicy(sizePolicy)
        self.cleanUpCams_BTN.setMinimumSize(QtCore.QSize(32, 32))
        self.cleanUpCams_BTN.setMaximumSize(QtCore.QSize(32, 32))
        self.cleanUpCams_BTN.setText("")
        self.cleanUpCams_BTN.setObjectName("cleanUpCams_BTN")
        self.tools_GRIDLAY.addWidget(self.cleanUpCams_BTN, 1, 0, 1, 1)
        self.lightsManager_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lightsManager_BTN.sizePolicy().hasHeightForWidth())
        self.lightsManager_BTN.setSizePolicy(sizePolicy)
        self.lightsManager_BTN.setMinimumSize(QtCore.QSize(32, 32))
        self.lightsManager_BTN.setMaximumSize(QtCore.QSize(32, 32))
        self.lightsManager_BTN.setText("")
        self.lightsManager_BTN.setObjectName("lightsManager_BTN")
        self.tools_GRIDLAY.addWidget(self.lightsManager_BTN, 1, 1, 1, 1)
        self.alignLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignLight_BTN.sizePolicy().hasHeightForWidth())
        self.alignLight_BTN.setSizePolicy(sizePolicy)
        self.alignLight_BTN.setMinimumSize(QtCore.QSize(32, 32))
        self.alignLight_BTN.setMaximumSize(QtCore.QSize(32, 32))
        self.alignLight_BTN.setText("")
        self.alignLight_BTN.setObjectName("alignLight_BTN")
        self.tools_GRIDLAY.addWidget(self.alignLight_BTN, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.tools_GRIDLAY)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lgtVis_GRIDLAY = QtGui.QGridLayout()
        self.lgtVis_GRIDLAY.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.lgtVis_GRIDLAY.setContentsMargins(0, -1, -1, -1)
        self.lgtVis_GRIDLAY.setObjectName("lgtVis_GRIDLAY")
        self.visSnapshot02_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visSnapshot02_BTN.sizePolicy().hasHeightForWidth())
        self.visSnapshot02_BTN.setSizePolicy(sizePolicy)
        self.visSnapshot02_BTN.setMinimumSize(QtCore.QSize(14, 14))
        self.visSnapshot02_BTN.setMaximumSize(QtCore.QSize(14, 14))
        self.visSnapshot02_BTN.setText("")
        self.visSnapshot02_BTN.setObjectName("visSnapshot02_BTN")
        self.lgtVis_GRIDLAY.addWidget(self.visSnapshot02_BTN, 0, 1, 1, 1)
        self.visSnapshot05_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visSnapshot05_BTN.sizePolicy().hasHeightForWidth())
        self.visSnapshot05_BTN.setSizePolicy(sizePolicy)
        self.visSnapshot05_BTN.setMinimumSize(QtCore.QSize(14, 14))
        self.visSnapshot05_BTN.setMaximumSize(QtCore.QSize(14, 14))
        self.visSnapshot05_BTN.setText("")
        self.visSnapshot05_BTN.setObjectName("visSnapshot05_BTN")
        self.lgtVis_GRIDLAY.addWidget(self.visSnapshot05_BTN, 1, 1, 1, 1)
        self.visSnapshot01_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visSnapshot01_BTN.sizePolicy().hasHeightForWidth())
        self.visSnapshot01_BTN.setSizePolicy(sizePolicy)
        self.visSnapshot01_BTN.setMinimumSize(QtCore.QSize(14, 14))
        self.visSnapshot01_BTN.setMaximumSize(QtCore.QSize(14, 14))
        self.visSnapshot01_BTN.setText("")
        self.visSnapshot01_BTN.setObjectName("visSnapshot01_BTN")
        self.lgtVis_GRIDLAY.addWidget(self.visSnapshot01_BTN, 0, 0, 1, 1)
        self.visSnapshot04_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visSnapshot04_BTN.sizePolicy().hasHeightForWidth())
        self.visSnapshot04_BTN.setSizePolicy(sizePolicy)
        self.visSnapshot04_BTN.setMinimumSize(QtCore.QSize(14, 14))
        self.visSnapshot04_BTN.setMaximumSize(QtCore.QSize(14, 14))
        self.visSnapshot04_BTN.setText("")
        self.visSnapshot04_BTN.setObjectName("visSnapshot04_BTN")
        self.lgtVis_GRIDLAY.addWidget(self.visSnapshot04_BTN, 1, 0, 1, 1)
        self.visSnapshot06_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visSnapshot06_BTN.sizePolicy().hasHeightForWidth())
        self.visSnapshot06_BTN.setSizePolicy(sizePolicy)
        self.visSnapshot06_BTN.setMinimumSize(QtCore.QSize(14, 14))
        self.visSnapshot06_BTN.setMaximumSize(QtCore.QSize(14, 14))
        self.visSnapshot06_BTN.setText("")
        self.visSnapshot06_BTN.setObjectName("visSnapshot06_BTN")
        self.lgtVis_GRIDLAY.addWidget(self.visSnapshot06_BTN, 2, 0, 1, 1)
        self.visSnapshot03_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visSnapshot03_BTN.sizePolicy().hasHeightForWidth())
        self.visSnapshot03_BTN.setSizePolicy(sizePolicy)
        self.visSnapshot03_BTN.setMinimumSize(QtCore.QSize(14, 14))
        self.visSnapshot03_BTN.setMaximumSize(QtCore.QSize(14, 14))
        self.visSnapshot03_BTN.setText("")
        self.visSnapshot03_BTN.setObjectName("visSnapshot03_BTN")
        self.lgtVis_GRIDLAY.addWidget(self.visSnapshot03_BTN, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.lgtVis_GRIDLAY)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lights_VERTLAY = QtGui.QVBoxLayout()
        self.lights_VERTLAY.setObjectName("lights_VERTLAY")
        self.defaultLights_GRIDLAY = QtGui.QGridLayout()
        self.defaultLights_GRIDLAY.setObjectName("defaultLights_GRIDLAY")
        self.spotLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spotLight_BTN.sizePolicy().hasHeightForWidth())
        self.spotLight_BTN.setSizePolicy(sizePolicy)
        self.spotLight_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.spotLight_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.spotLight_BTN.setText("")
        self.spotLight_BTN.setObjectName("spotLight_BTN")
        self.defaultLights_GRIDLAY.addWidget(self.spotLight_BTN, 0, 0, 1, 1)
        self.pointLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointLight_BTN.sizePolicy().hasHeightForWidth())
        self.pointLight_BTN.setSizePolicy(sizePolicy)
        self.pointLight_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.pointLight_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.pointLight_BTN.setText("")
        self.pointLight_BTN.setObjectName("pointLight_BTN")
        self.defaultLights_GRIDLAY.addWidget(self.pointLight_BTN, 0, 1, 1, 1)
        self.areaLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaLight_BTN.sizePolicy().hasHeightForWidth())
        self.areaLight_BTN.setSizePolicy(sizePolicy)
        self.areaLight_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.areaLight_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.areaLight_BTN.setText("")
        self.areaLight_BTN.setObjectName("areaLight_BTN")
        self.defaultLights_GRIDLAY.addWidget(self.areaLight_BTN, 0, 2, 1, 1)
        self.directionalLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directionalLight_BTN.sizePolicy().hasHeightForWidth())
        self.directionalLight_BTN.setSizePolicy(sizePolicy)
        self.directionalLight_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.directionalLight_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.directionalLight_BTN.setText("")
        self.directionalLight_BTN.setObjectName("directionalLight_BTN")
        self.defaultLights_GRIDLAY.addWidget(self.directionalLight_BTN, 0, 3, 1, 1)
        self.ambientLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ambientLight_BTN.sizePolicy().hasHeightForWidth())
        self.ambientLight_BTN.setSizePolicy(sizePolicy)
        self.ambientLight_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.ambientLight_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.ambientLight_BTN.setText("")
        self.ambientLight_BTN.setObjectName("ambientLight_BTN")
        self.defaultLights_GRIDLAY.addWidget(self.ambientLight_BTN, 0, 4, 1, 1)
        self.volumeLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeLight_BTN.sizePolicy().hasHeightForWidth())
        self.volumeLight_BTN.setSizePolicy(sizePolicy)
        self.volumeLight_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.volumeLight_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.volumeLight_BTN.setText("")
        self.volumeLight_BTN.setObjectName("volumeLight_BTN")
        self.defaultLights_GRIDLAY.addWidget(self.volumeLight_BTN, 0, 5, 1, 1)
        self.lights_VERTLAY.addLayout(self.defaultLights_GRIDLAY)
        self.rendererLights_GRIDLAY = QtGui.QGridLayout()
        self.rendererLights_GRIDLAY.setObjectName("rendererLights_GRIDLAY")
        self.aiAreaLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aiAreaLight_BTN.sizePolicy().hasHeightForWidth())
        self.aiAreaLight_BTN.setSizePolicy(sizePolicy)
        self.aiAreaLight_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.aiAreaLight_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.aiAreaLight_BTN.setText("")
        self.aiAreaLight_BTN.setObjectName("aiAreaLight_BTN")
        self.rendererLights_GRIDLAY.addWidget(self.aiAreaLight_BTN, 0, 0, 1, 1)
        self.aiSkyDomeLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aiSkyDomeLight_BTN.sizePolicy().hasHeightForWidth())
        self.aiSkyDomeLight_BTN.setSizePolicy(sizePolicy)
        self.aiSkyDomeLight_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.aiSkyDomeLight_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.aiSkyDomeLight_BTN.setText("")
        self.aiSkyDomeLight_BTN.setObjectName("aiSkyDomeLight_BTN")
        self.rendererLights_GRIDLAY.addWidget(self.aiSkyDomeLight_BTN, 0, 1, 1, 1)
        self.aiMeshLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aiMeshLight_BTN.sizePolicy().hasHeightForWidth())
        self.aiMeshLight_BTN.setSizePolicy(sizePolicy)
        self.aiMeshLight_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.aiMeshLight_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.aiMeshLight_BTN.setText("")
        self.aiMeshLight_BTN.setObjectName("aiMeshLight_BTN")
        self.rendererLights_GRIDLAY.addWidget(self.aiMeshLight_BTN, 0, 2, 1, 1)
        self.aiPhotometricLight_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aiPhotometricLight_BTN.sizePolicy().hasHeightForWidth())
        self.aiPhotometricLight_BTN.setSizePolicy(sizePolicy)
        self.aiPhotometricLight_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.aiPhotometricLight_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.aiPhotometricLight_BTN.setText("")
        self.aiPhotometricLight_BTN.setObjectName("aiPhotometricLight_BTN")
        self.rendererLights_GRIDLAY.addWidget(self.aiPhotometricLight_BTN, 0, 3, 1, 1)
        self.aiLightPortal_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aiLightPortal_BTN.sizePolicy().hasHeightForWidth())
        self.aiLightPortal_BTN.setSizePolicy(sizePolicy)
        self.aiLightPortal_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.aiLightPortal_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.aiLightPortal_BTN.setText("")
        self.aiLightPortal_BTN.setObjectName("aiLightPortal_BTN")
        self.rendererLights_GRIDLAY.addWidget(self.aiLightPortal_BTN, 0, 4, 1, 1)
        self.aiPhysicalSky_BTN = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aiPhysicalSky_BTN.sizePolicy().hasHeightForWidth())
        self.aiPhysicalSky_BTN.setSizePolicy(sizePolicy)
        self.aiPhysicalSky_BTN.setMinimumSize(QtCore.QSize(16, 16))
        self.aiPhysicalSky_BTN.setMaximumSize(QtCore.QSize(16, 16))
        self.aiPhysicalSky_BTN.setText("")
        self.aiPhysicalSky_BTN.setObjectName("aiPhysicalSky_BTN")
        self.rendererLights_GRIDLAY.addWidget(self.aiPhysicalSky_BTN, 0, 5, 1, 1)
        self.lights_VERTLAY.addLayout(self.rendererLights_GRIDLAY)
        self.horizontalLayout.addLayout(self.lights_VERTLAY)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.config_BTN = QtGui.QPushButton(self.centralwidget)
        self.config_BTN.setMaximumSize(QtCore.QSize(20, 20))
        self.config_BTN.setText("")
        self.config_BTN.setObjectName("config_BTN")
        self.horizontalLayout.addWidget(self.config_BTN)
        miniLightingTools_MW.setCentralWidget(self.centralwidget)

        self.retranslateUi(miniLightingTools_MW)
        QtCore.QMetaObject.connectSlotsByName(miniLightingTools_MW)

    def retranslateUi(self, miniLightingTools_MW):
        miniLightingTools_MW.setWindowTitle(QtGui.QApplication.translate("miniLightingTools_MW", "Mini Lighting Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.simpleIsolate_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Toggle Isolate Lights", None, QtGui.QApplication.UnicodeUTF8))
        self.lookThru_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.aimLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.specularConstrain_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.cleanUpCams_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.lightsManager_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.alignLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.visSnapshot02_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.visSnapshot05_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.visSnapshot01_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.visSnapshot04_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.visSnapshot06_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.visSnapshot03_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.spotLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.pointLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.areaLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.directionalLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.ambientLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.aiAreaLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.aiSkyDomeLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.aiMeshLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.aiPhotometricLight_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.aiLightPortal_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))
        self.aiPhysicalSky_BTN.setToolTip(QtGui.QApplication.translate("miniLightingTools_MW", "Aim: Select lights first, target last", None, QtGui.QApplication.UnicodeUTF8))

